Update Jenkinsfile v0.1

diff --git a/MP420244/Sprawozdanie7/Jenkinsfile b/MP420244/Sprawozdanie7/Jenkinsfile
--- a/MP420244/Sprawozdanie7/Jenkinsfile
+++ b/MP420244/Sprawozdanie7/Jenkinsfile
@@ -1,23 +1,90 @@
 pipeline {
     agent any
 
+    environment {
+        BUILD_DIR = 'build'
+        ARTIFACT_BUILD = 'app-build.tar.gz'
+        ARTIFACT_IMAGE = 'app-image.tar.gz'
+        DOCKERFILE_BUILD_PATH = 'MP420244/Sprawozdanie3/Dockerfile.build'
+        DOCKERFILE_TEST_PATH = 'MP420244/Sprawozdanie3/Dockerfile.test'
+    }
+
     stages {
-        stage('Build') {
+        stage('Clean up') {
             steps {
-                echo 'Building...'
-                // Tutaj możesz dodać kroki budowania, np. kompilację kodu
+                echo 'STAGE: CLEAN UP'
+                echo 'Cleaning up...'
+
+                cleanWs()
+
+                script {
+                    sh "docker system prune -af || true"
+                    sh "rm -rf ${BUILD_DIR} ${ARTIFACT_BUILD} || true"
+                    sh "ls -l"
+                }
+            }
+        }
+        stage('Build') {
+
+            steps {
+                echo 'STAGE: BUILD'
+                echo 'Building application...'
+
+                script {
+                    sh "docker build --no-cache -t my-app-build -f ${DOCKERFILE_BUILD_PATH} ."
+                    sh "docker run --rm my-app-build tar czf - /app/build > ${ARTIFACT_BUILD}"
+                }
             }
         }
         stage('Test') {
+
             steps {
-                echo 'Testing...'
-                // Tutaj możesz dodać kroki testowania, np. uruchamianie testów jednostkowych
+                echo 'STAGE: TEST'
+                echo 'Testing application...'
+
+                script {
+                    def status = sh(
+                        script: "docker run --rm my-app-test > test-results.txt 2>&1",
+                        returnStatus: true
+                    )
+
+                    if (status != 0) {
+                        currentBuild.result = 'FAILURE'
+                        error("Tests failed. See test-results.txt")
+                    }
+                }
+            }
+        }
+        stage ('Package') {
+            steps {
+                echo 'STAGE: PACKAGE'
+                echo 'Packaging docker image...'
+
+                script {
+                    sh "docker save my-app-build | gzip > ${ARTIFACT_IMAGE}"
+                }
             }
         }
         stage('Deploy') {
             steps {
-                echo 'Deploying...'
-                // Tutaj możesz dodać kroki wdrażania, np. przesyłanie aplikacji na serwer
+                echo 'STAGE: DEPLOY'
+                echo 'Simulating deployment in fresh container...'
+
+                script {
+                    sh '''
+                    docker load < ${ARTIFACT_IMAGE}
+                    docker run --rm my-app-build make clean && make && ./test-library.out
+                    '''
+                }
+            }
+        }
+        stage('Publish') {
+            agent any
+            
+            steps {
+                echo 'STAGE: PUBLISH'
+
+                archiveArtifacts artifacts: "*.tag.gz, test-results.txt", fingerprint: true
             }
         }
     }
